### ISSUE TITLE
Missing Path values for some files/dirs

### ISSUE THREAD

**Issue by Sim4n6** [msuhanov/dfir_ntfs#7]
This small [MFT](https://filebin.net/92h3a3ytbb00nldo) when  it get parsed using the script ntfs_parser. It produces an CSV with some records without Path name. 

Records are : 3377699720527884 - 3659174697238541- 3940649673949198 - 4222124650659855

I'm not sure if it is anomaly, but I am sharing it any way for testing purpose.

**Comment by msuhanov** [comment]
These are file record segments #12, #13, #14, and #15. Each one has the $STANDARD_INFORMATION attribute, but none of them has the $FILE_NAME attribute (just checked it again using a HEX editor).

So, the tool is printing data as is.

**Comment by Sim4n6** [comment]
Alright, thank u for ur response
