### ISSUE TITLE
NTFS_parser --all-mft in action

### ISSUE THREAD

**Issue by Sim4n6** [msuhanov/dfir_ntfs#8]
Just a small question, performing `ntfs_parser --all-mft <input file (raw image)> <volume offset (in bytes)> <output file (CSV)>` will produce a single CSV file of a merged $MFT from the main volume and the different VSS ?

**Comment by msuhanov** [comment]
Yes, it will produce a single file. And each entry will contain information about its source (a main volume or a shadow copy).

**Comment by Sim4n6** [comment]
Thanks
